version: "3.8"

services:

  mysql:
    image: mysql:8.4
    container_name: mysql-db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productdb
      MYSQL_USER: springuser
      MYSQL_PASSWORD: spring123

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - spring-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2-alpine
    container_name: redis-cache

    restart: always

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis-data:/data

    networks:
      - spring-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  product-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: product-service

    restart: always

    ports:
      - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/productdb
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: spring123

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    networks:
      - spring-network

volumes:
  mysql-data:
  redis-data:

networks:
  spring-network:
    driver: bridge